### ISSUE TITLE
Automation afval vandaag

### ISSUE THREAD

**Issue by maartenvr98** [Cadsters/acv-hass-component#18]
Is het mogelijk om een automation te maken als er vandaag (of morgen) een kliko aan de weg moet? 

Ik kom er nog niet achter hoe ik dat voor elkaar kan krijgen.

**Comment by Cadsters** [comment]
Dag,
Ik weet niet wat je kennisniveau is dus geen idee of je hier wat aan hebt.
Je moet om deze automation te gebruiken twee input-booleans aanmaken, vakantie en notify_trash.
Bij action (in de automation) moet je de service notify aanpassen aan de door jou ingestelde notifier.
```yaml
- id: 'Afval Melding'
  alias: 'Afval Melding'
  trigger:
    - platform: time
      at: '19:30:00'
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.vakantie
        state: 'off'
      - condition: state
        entity_id: input_boolean.notify_trash
        state: 'on'
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_gft.state) }}'
        - condition: template
          value_template: '{{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_rest.state) }}'
        - condition: template
          value_template: '{{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_pmd.state) }}'
        - condition: template
          value_template: '{{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_papier.state) }}'
  action:
  - service: notify.ALL_DEVICES
    data_template:
      message: >-
        {% if (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_gft.state) %}
           De groene bak wordt morgen geleegd!
        {% endif %}
        {% if (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_rest.state) %}
           De grijze bak wordt morgen geleegd!
        {% endif %}
        {% if (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_pmd.state) %}
           Plastic wordt morgen opgehaald!
        {% endif %}
        {% if (as_timestamp(now()) + (24*3600)) | timestamp_custom("%Y-%m-%d",true) == (states.sensor.afval_papier.state) %}
           Papier wordt morgen opgehaald!
        {% endif %}
```
