### ISSUE TITLE
Question: how to format date

### ISSUE THREAD

**Issue by achilleus68** [Cadsters/acv-hass-component#5]
Hi,

I can not find another way to contact you, so misusing github:
How can I format the date? I've tried to expand your integration as follows, but this does not work

Dates are shown as follows: 
![image](https://user-images.githubusercontent.com/1582516/71696595-b491b580-2db5-11ea-9f71-f8d9e08bb68c.png)

```
- platform: acv
  postcode: !secret
  housenumber: !secret
  resources:
    - today
    - tomorrow
    - grey
    - green
    - paper
    - packages
    - textile

- platform: template
  sensors:
    acv_green:
      entity_id: sensor.acv_green
      value_template:  "{{ strptime(sensor.acv_green.date, '%d-%m-%y') }}"

```
